site_name: RICOH360 Viewer Local Install
site_url: https://codetricity.github.io/ricoh360-viewer-offline/
site_author: Oppkey
copyright: © Oppkey 2024

theme:
  name: material

plugins:
  - search
  - encryptcontent:
      global_password: 'RicohViewerRocks'
  # - with-pdf:
  #     author: Oppkey
  #     copyright: © Oppkey 2024
  #     cover_title: RICOH360 Viewer Local Install
  #     cover_subtitle: community document - last updated Oct 7, 2024


nav:
  - Home: index.md
  - Example: code_examples.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences