site_name: RICOH360 Viewer Local Install
theme:
  name: material

plugins:
  - search
  - encryptcontent:
      global_password: 'RicohViewerRocks'

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences